# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: React
  items:
    - label: "Initial"
      link: "/react/initial"
    - label: "JSX"
      link: "/react/jsx"
    - label: "Props & State"
      link: "/react/props-state"
    - label: "Life cycles"
      link: "/react/lifecycle"
    - label: "List & Ref"
      link: "/react/list-ref"
    - label: "Forms"
      link: "/react/forms"
    - label: "Hooks"
      link: "/react/base-hooks"
    - label: "SPA & Routing"
      link: "/react/spa-routing"
    - label: "React patterns"
      link: "/react/patterns"
- label: "Redux"
  items:
    - label: "Essentials"
      link: "/redux/essentials"
    - label: "React Redux"
      link: "/redux/react-redux"
    - label: "Redux Thunk"
      link: "/redux/redux-thunk"
- label: "Projects"
  link: "/projects"
