# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: React
  items:
    - label: "Initial"
      link: "/react/initial"
    - label: "JSX"
      link: "/react/jsx"
    - label: "Props & State"
      link: "/react/props-state"
    - label: "Life cycles"
      link: "/react/lifecycle"
    - label: "List & Ref"
      link: "/react/list-ref"
    - label: "Forms"
      link: "/react/forms"
    - label: "Hooks"
      link: "/react/base-hooks"
    - label: "SPA & Routing"
      link: "/react/spa-routing"
    - label: "Redux"
      link: "/react/redux"
    - label: "Projects"
      link: "/react/projects"
