# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: React
  items:
    - label: "Initial"
      link: "/react/initial"
    - label: "JSX"
      link: "/react/jsx"
    - label: "Props & State"
      link: "/react/props-state"
    - label: "Life cycles"
      link: "/react/lifecycle"
    - label: "List & Ref"
      link: "/react/list-ref"
    - label: "Forms"
      link: "/react/forms"
    - label: "Hooks"
      link: "/react/base-hooks"
    - label: "SPA & Routing"
      link: "/react/spa-routing"
    - label: "GraphQL"
      link: "/react/graphql"
    - label: "JWT & Authorization"
      link: "/react/jwt"
    - label: "Prop Types"
      link: "/react/prop-types"
    - label: "Optimize Components"
      link: "/react/react-optimize-components"
    - label: "Advanced Hooks"
      link: "/react/advanced-hooks"
    - label: "Context"
      link: "/react/context"
    - label: "React patterns"
      link: "/react/patterns"
- label: "Redux"
  items:
    - label: "Essentials"
      link: "/redux/essentials"
    # - label: "Own Redux"
    # link: "/redux/own-redux"
    - label: "React Redux"
      link: "/redux/react-redux"
    - label: "Redux Async Flow"
      link: "/redux/redux-async-flow"
- label: "Projects"
  link: "/projects"
